name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: WeihanLi/dotnet-install@v0.2.0
        with:
          version: 10.0.x

      - name: Restore dependencies
        run: dotnet restore k6-tester.slnx

      - name: Build
        run: dotnet build k6-tester.slnx -c Release --no-restore

      - name: Test
        run: |
          cd test/k6-tester.Tests/
          dotnet add package GitHubActionsTestLogger
          dotnet test -c Release --logger "GitHubActions"
